const data = [
    {
      "children": [
        {
          "children": [
            {
              "createTime": 1512614056000,
              "id": 20,
              "importantLevel": 1,
              "locator": "",
              "locatorType": 0,
              "name": "tampA-A-A",
              "parentId": 4,
              "siteId": 19,
              "sort": 0,
              "type": 1,
              "updateTime": 1512614056000,
              "urlInfoId": 48
            },
            {
              "createTime": 1512614056000,
              "id": 26,
              "importantLevel": 1,
              "locator": "",
              "locatorType": 0,
              "name": "tampA-A-A",
              "parentId": 4,
              "siteId": 19,
              "sort": 0,
              "type": 1,
              "updateTime": 1512614056000,
              "urlInfoId": 48
            },
            {
              "createTime": 1512614056000,
              "id": 29,
              "importantLevel": 1,
              "locator": "",
              "locatorType": 0,
              "name": "tampA-A-A",
              "parentId": 4,
              "siteId": 19,
              "sort": 0,
              "type": 1,
              "updateTime": 1512614056000,
              "urlInfoId": 48
            },
            {
              "createTime": 1512614056000,
              "id": 32,
              "importantLevel": 1,
              "locator": "",
              "locatorType": 0,
              "name": "tampA-A-A",
              "parentId": 4,
              "siteId": 19,
              "sort": 0,
              "type": 1,
              "updateTime": 1512614056000,
              "urlInfoId": 48
            }
          ],
          "createTime": 1512614056000,
          "id": 4,
          "importantLevel": 1,
          "locator": "",
          "locatorType": 0,
          "name": "tampA-A",
          "parentId": 1,
          "siteId": 19,
          "sort": 0,
          "type": 1,
          "updateTime": 1512614056000,
          "urlInfoId": 48
        },
        {
          "createTime": 1512614056000,
          "id": 23,
          "importantLevel": 1,
          "locator": "",
          "locatorType": 0,
          "name": "tampA-A",
          "parentId": 1,
          "siteId": 19,
          "sort": 0,
          "type": 1,
          "updateTime": 1512614056000,
          "urlInfoId": 48
        },
        {
          "createTime": 1512614056000,
          "id": 17,
          "importantLevel": 1,
          "locator": "",
          "locatorType": 0,
          "name": "tampA-A",
          "parentId": 1,
          "siteId": 19,
          "sort": 0,
          "type": 1,
          "updateTime": 1512614056000,
          "urlInfoId": 48
        }
      ],
      "createTime": 1512614056000,
      "id": 1,
      "importantLevel": 1,
      "locator": "",
      "locatorType": 0,
      "name": "tempA",
      "siteId": 19,
      "sort": 0,
      "type": 1,
      "updateTime": 1512614056000,
      "urlInfoId": 48
    },
    {
      "children": [
        {
          "children": [
            {
              "createTime": 1512614056000,
              "id": 24,
              "importantLevel": 1,
              "locator": "",
              "locatorType": 0,
              "name": "tempB-B-B",
              "parentId": 5,
              "siteId": 19,
              "sort": 0,
              "type": 1,
              "updateTime": 1512614056000,
              "urlInfoId": 48
            },
            {
              "createTime": 1512614056000,
              "id": 27,
              "importantLevel": 1,
              "locator": "",
              "locatorType": 0,
              "name": "tempB-B-B",
              "parentId": 5,
              "siteId": 19,
              "sort": 0,
              "type": 1,
              "updateTime": 1512614056000,
              "urlInfoId": 48
            },
            {
              "createTime": 1512614056000,
              "id": 30,
              "importantLevel": 1,
              "locator": "",
              "locatorType": 0,
              "name": "tempB-B-B",
              "parentId": 5,
              "siteId": 19,
              "sort": 0,
              "type": 1,
              "updateTime": 1512614056000,
              "urlInfoId": 48
            },
            {
              "createTime": 1512614056000,
              "id": 33,
              "importantLevel": 1,
              "locator": "",
              "locatorType": 0,
              "name": "tempB-B-B",
              "parentId": 5,
              "siteId": 19,
              "sort": 0,
              "type": 1,
              "updateTime": 1512614056000,
              "urlInfoId": 48
            }
          ],
          "createTime": 1512614056000,
          "id": 5,
          "importantLevel": 1,
          "locator": "",
          "locatorType": 0,
          "name": "tempB-B",
          "parentId": 2,
          "siteId": 19,
          "sort": 0,
          "type": 1,
          "updateTime": 1512614056000,
          "urlInfoId": 48
        },
        {
          "createTime": 1512614056000,
          "id": 18,
          "importantLevel": 1,
          "locator": "",
          "locatorType": 0,
          "name": "tempB-B",
          "parentId": 2,
          "siteId": 19,
          "sort": 0,
          "type": 1,
          "updateTime": 1512614056000,
          "urlInfoId": 48
        },
        {
          "createTime": 1512614056000,
          "id": 21,
          "importantLevel": 1,
          "locator": "",
          "locatorType": 0,
          "name": "tempB-B",
          "parentId": 2,
          "siteId": 19,
          "sort": 0,
          "type": 1,
          "updateTime": 1512614056000,
          "urlInfoId": 48
        }
      ],
      "createTime": 1512614056000,
      "id": 2,
      "importantLevel": 1,
      "locator": "",
      "locatorType": 0,
      "name": "tampB",
      "siteId": 19,
      "sort": 0,
      "type": 2,
      "updateTime": 1512614056000,
      "urlInfoId": 48
    },
    {
      "children": [
        {
          "children": [
            {
              "createTime": 1512614056000,
              "id": 25,
              "importantLevel": 1,
              "locator": "",
              "locatorType": 0,
              "name": "tampC-C-C",
              "parentId": 6,
              "siteId": 19,
              "sort": 0,
              "type": 1,
              "updateTime": 1512614056000,
              "urlInfoId": 48
            },
            {
              "createTime": 1512614056000,
              "id": 28,
              "importantLevel": 1,
              "locator": "",
              "locatorType": 0,
              "name": "tampC-C-C",
              "parentId": 6,
              "siteId": 19,
              "sort": 0,
              "type": 1,
              "updateTime": 1512614056000,
              "urlInfoId": 48
            },
            {
              "createTime": 1512614056000,
              "id": 31,
              "importantLevel": 1,
              "locator": "",
              "locatorType": 0,
              "name": "tampC-C-C",
              "parentId": 6,
              "siteId": 19,
              "sort": 0,
              "type": 1,
              "updateTime": 1512614056000,
              "urlInfoId": 48
            },
            {
              "createTime": 1512614056000,
              "id": 34,
              "importantLevel": 1,
              "locator": "",
              "locatorType": 0,
              "name": "tampC-C-C",
              "parentId": 6,
              "siteId": 19,
              "sort": 0,
              "type": 1,
              "updateTime": 1512614056000,
              "urlInfoId": 48
            }
          ],
          "createTime": 1512614056000,
          "id": 6,
          "importantLevel": 1,
          "locator": "",
          "locatorType": 0,
          "name": "tampC-C",
          "parentId": 3,
          "siteId": 19,
          "sort": 0,
          "type": 1,
          "updateTime": 1512614056000,
          "urlInfoId": 48
        },
        {
          "createTime": 1512614056000,
          "id": 22,
          "importantLevel": 1,
          "locator": "",
          "locatorType": 0,
          "name": "tampC-C",
          "parentId": 3,
          "siteId": 19,
          "sort": 0,
          "type": 1,
          "updateTime": 1512614056000,
          "urlInfoId": 48
        },
        {
          "createTime": 1512614056000,
          "id": 19,
          "importantLevel": 1,
          "locator": "",
          "locatorType": 0,
          "name": "tampC-C",
          "parentId": 3,
          "siteId": 19,
          "sort": 0,
          "type": 1,
          "updateTime": 1512614056000,
          "urlInfoId": 48
        }
      ],
      "createTime": 1512614056000,
      "id": 3,
      "importantLevel": 1,
      "locator": "",
      "locatorType": 0,
      "name": "tempC",
      "siteId": 19,
      "sort": 0,
      "type": 1,
      "updateTime": 1512614056000,
      "urlInfoId": 48
    }
  ];

export {data}